services:
  api:
    build: ..
    ports:
      - "8008:8008"
    container_name: book_api
    env_file:
      - ../.env
    depends_on:
      - mongo
      - redis

  scheduler:
    build: ..
    container_name: scheduler
    env_file:
      - ../.env
    command: python scheduler/jobs.py
    depends_on:
      - mongo

  crawler:
    build: ..
    container_name: crawler
    env_file:
      - ../.env
    command: python scripts/run_crawl_once.py
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379

volumes:
  mongo_data:
